<h1>Nested Controllers in Zend Framework</h1>
<ul>
    <li>Admin
        <ul>
            <li>Page
                <ul>
                    <li>Sub Page    
                        <ul>
                            <li>Display
                                <ul>
                                    <li><a href="<?php echo $this->baseUrl('admin/page/sub-page/display'); ?>">Index</a></li>
                                    <li><a href="<?php echo $this->baseUrl('admin/page/sub-page/display/edit'); ?>">Edit</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li>Display
                        <ul>
                            <li><a href="<?php echo $this->baseUrl('admin/page/display'); ?>">Index</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>Standard
                <ul>
                    <li><a href="<?php echo $this->baseUrl('admin/standard'); ?>">Index</a></li>
                </ul>
            </li>
        </ul>
    </li>
</ul>